### 기본 List

In [3]:
list_a = [1, 2, 3]
print(list_a)
print(type(list_a))

[1, 2, 3]
<class 'list'>


### List -> NumPy 변환.

In [8]:
import numpy as np

array = np.array(list_a)
print(f'array: {array}')
print(f'type: {type(array)}')
print(f'size: {array.size}')
print(f'dtype: {array.dtype}')
print(f'3번째 인덱스 접근: {array[2]}')

array: [1 2 3]
type: <class 'numpy.ndarray'>
size: 3
dtype: int64
3번째 인덱스 접근: 3


### NumPy 배열 초기화.

In [14]:
array_1 = np.arange(4)
print(f'array_1: {array_1}')

array_2 = np.zeros((4, 4), dtype=float)
print(f'array_2: \n{array_2}')

array_3 = np.ones((4, 4), dtype=str)
print(f'array_2: \n{array_3}')

array_4 = np.ones((3, 3), dtype=int)
print(f'array_2: \n{array_4}')

array_1: [0 1 2 3]
array_2: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array_2: 
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
array_2: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [17]:
array_5 = np.random.randint(0, 10, (4, 4))
print(f'array_5: \n{array_5}')

array_6 = np.random.normal(0, 1, (3, 3))
print(f'array_6: \n{array_6}')

array_5: 
[[6 1 5 2]
 [6 9 8 1]
 [0 7 1 6]
 [4 2 6 2]]
array_6: 
[[-0.05551072  0.3817595  -0.86927747]
 [ 0.72841876 -0.34206703 -0.90390527]
 [ 1.02074306  1.04072558  0.61319002]]


NumPy 배열 합치기

In [30]:
# 가로
array_6 = np.array([1, 2, 3])
array_7 = np.array([3, 2, 1])
array_8 = np.concatenate([array_6, array_7])
print(f'shape: {array_8.shape}')
print(f'array_8: {array_8}')

# 세로
array_6 = array_6.reshape(1,3)
array_7 = array_7.reshape(1,3)
array_9 = np.concatenate([array_6, array_7], axis=0)
print(f'shape: {array_9.shape}')
print(f'array_9: \n{array_9}')

shape: (6,)
array_8: [1 2 3 3 2 1]
shape: (2, 3)
array_9: 
[[1 2 3]
 [3 2 1]]


NumPy 배열 형태 바꾸기.

In [22]:
array_a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'array_a: {array_a}')
array_b = array_a.reshape((3, 3))
print(f'array_b: \n{array_b}')

array_a: [1 2 3 4 5 6 7 8 9]
array_b: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### NumPy 배열 나누기.

In [34]:
# 2x4 행렬
array_c = np.arange(8).reshape(2, 4)
# 2번 인덱스, 행렬로 치면 3열을 기준으로 자름.
left, right = np.split(array_c, [2], axis=1)
print(f'left.shape: {left.shape}')
print(f'right.shape: {right.shape}')
print(f'array_c: \n{array_c}')
print(f'left: \n{left}')
print(f'rigth: \n{right}')

left.shape: (2, 2)
right.shape: (2, 2)
array_c: 
[[0 1 2 3]
 [4 5 6 7]]
left: 
[[0 1]
 [4 5]]
rigth: 
[[2 3]
 [6 7]]
