### 기본 List

In [2]:
list_a = [1, 2, 3]
print(list_a)
print(type(list_a))

[1, 2, 3]
<class 'list'>


### List -> NumPy 변환.

In [3]:
import numpy as np

array = np.array(list_a)
print(f'array: {array}')
print(f'type: {type(array)}')
print(f'size: {array.size}')
print(f'dtype: {array.dtype}')
print(f'3번째 인덱스 접근: {array[2]}')

array: [1 2 3]
type: <class 'numpy.ndarray'>
size: 3
dtype: int64
3번째 인덱스 접근: 3


### NumPy 배열 초기화.

In [4]:
array_1 = np.arange(4)
print(f'array_1: {array_1}')

array_2 = np.zeros((4, 4), dtype=float)
print(f'array_2: \n{array_2}')

array_3 = np.ones((4, 4), dtype=str)
print(f'array_2: \n{array_3}')

array_4 = np.ones((3, 3), dtype=int)
print(f'array_2: \n{array_4}')

array_1: [0 1 2 3]
array_2: 
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
array_2: 
[['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']
 ['1' '1' '1' '1']]
array_2: 
[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [5]:
array_5 = np.random.randint(0, 10, (4, 4))
print(f'array_5: \n{array_5}')

array_6 = np.random.normal(0, 1, (3, 3))
print(f'array_6: \n{array_6}')

array_5: 
[[7 6 8 0]
 [0 8 6 1]
 [5 0 2 3]
 [5 8 5 8]]
array_6: 
[[-0.28392044  1.28048147  0.76126426]
 [ 0.95249548  0.562699   -0.19991794]
 [ 1.11443398  1.0083448  -0.66387089]]


NumPy 배열 합치기

In [6]:
# 가로
array_6 = np.array([1, 2, 3])
array_7 = np.array([3, 2, 1])
array_8 = np.concatenate([array_6, array_7])
print(f'shape: {array_8.shape}')
print(f'array_8: {array_8}')

# 세로
array_6 = array_6.reshape(1,3)
array_7 = array_7.reshape(1,3)
array_9 = np.concatenate([array_6, array_7], axis=0)
print(f'shape: {array_9.shape}')
print(f'array_9: \n{array_9}')

shape: (6,)
array_8: [1 2 3 3 2 1]
shape: (2, 3)
array_9: 
[[1 2 3]
 [3 2 1]]


NumPy 배열 형태 바꾸기.

In [7]:
array_a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
print(f'array_a: {array_a}')
array_b = array_a.reshape((3, 3))
print(f'array_b: \n{array_b}')

array_a: [1 2 3 4 5 6 7 8 9]
array_b: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


### NumPy 배열 나누기.

In [8]:
# 2x4 행렬
array_c = np.arange(8).reshape(2, 4)
# 2번 인덱스, 행렬로 치면 3열을 기준으로 자름.
left, right = np.split(array_c, [2], axis=1)
print(f'left.shape: {left.shape}')
print(f'right.shape: {right.shape}')
print(f'array_c: \n{array_c}')
print(f'left: \n{left}')
print(f'rigth: \n{right}')

left.shape: (2, 2)
right.shape: (2, 2)
array_c: 
[[0 1 2 3]
 [4 5 6 7]]
left: 
[[0 1]
 [4 5]]
rigth: 
[[2 3]
 [6 7]]


### NumPy 연산.

In [12]:
array_d = np.random.randint(1, 10, size=4).reshape(2, 2)
print(f'array_d: \n{array_d}')

result_array_d = array_d * 10
print(f'result_array_d: \n{result_array_d}')

array_d: 
[[1 1]
 [9 4]]
result_array_d: 
[[10 10]
 [90 40]]


### 서로 다른 형태의 행렬을 계산할 수 있도록 도와주는 브로드캐스팅

In [14]:
array_e = np.arange(4).reshape(2, 2)    # (2 x 2 행렬)
array_f = np.arange(2)                  # (1 x 2 행렬)
array_g = array_e + array_f
print(f'array_g: \n{array_g}')

array_g: 
[[0 2]
 [2 4]]


In [19]:
array1 = np.arange(0, 8).reshape(2, 4)      # (2 x 4 행렬)
array2 = np.arange(0, 8).reshape(2, 4)      # (2 x 4 행렬)
array3 = np.concatenate([array1, array2], axis=0)
print(f'array3: \n{array3}')
array4 = np.arange(0, 4).reshape(4, 1)      # (4 x 1 행렬)
print(f'array4: \n{array4}')
print(f'array3 + array4: \n{array3 + array4}')

array3: 
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
array4: 
[[0]
 [1]
 [2]
 [3]]
array3 + array4: 
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


### 마스킹 연산

In [23]:
array1 = np.arange(16).reshape(4, 4)
print(f'array1: \n{array1}')
array2 = array1 < 10
print(f'array2: \n{array2}')
array1[array2] = 100
print(f'array1: \n{array1}')

array1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array2: 
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
array1: 
[[100 100 100 100]
 [100 100 100 100]
 [100 100  10  11]
 [ 12  13  14  15]]


### 집계 함수.

In [26]:
array1 = np.arange(16).reshape(4, 4)
print(f'array1: \n{array1}')
print(f'array1 최댓값: {np.max(array1)}')
print(f'array1 최솟값: {np.min(array1)}')
print(f'array1 합계: {np.sum(array1)}')
print(f'array1 평균값: {np.mean(array1)}')

array1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1 최댓값: 15
array1 최솟값: 0
array1 합계: 120
array1 평균값: 7.5


In [29]:
print(f'array1: \n{array1}')
print(f'array1 각 열에 대한 합계: \n{np.sum(array1, axis=0)}')

array1: 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
array1 각 열에 대한 합계: 
[24 28 32 36]


### 저장 및 불러오기.

In [35]:
array1 = np.arange(0, 10)
print(f'array1: \n{array1}')
# np.savez(): 1 개의 Numpy 객체를 파일형태로 저장 가능.
np.save('saved.npy', array1)

result = np.load('saved.npy')
print(f'result: \n{result}')

array1: 
[0 1 2 3 4 5 6 7 8 9]
result: 
[0 1 2 3 4 5 6 7 8 9]


In [42]:
array1 = np.arange(0, 10)
print(f'array1: \n{array1}')
array2 = np.arange(10, 20)
print(f'array2: \n{array2}')
# np.savez(): 복수 개의 Numpy 객체를 파일형태로 저장 가능.
np.savez('saved.npz', array1 = array1, array2 = array2)

print('\n\n')

result = np.load('saved.npz')
print(f'result: \n{result}')
print(f'result["array1"]: {result['array1']}')
print(f'result["array2"]: {result['array2']}')

array1: 
[0 1 2 3 4 5 6 7 8 9]
array2: 
[10 11 12 13 14 15 16 17 18 19]



result: 
NpzFile 'saved.npz' with keys: array1, array2
result["array1"]: [0 1 2 3 4 5 6 7 8 9]
result["array2"]: [10 11 12 13 14 15 16 17 18 19]


### 원소의 정렬.

In [47]:
array1 = np.array([5, 9, 10, 3, 1, 4])
print(f'array1: {array1}')
array1.sort()
print(f'array1 정렬(오름차순): {array1}')
print(f'array1 정렬(인덱싱으로 내림차순 구현): {array1[::-1]}')

array1: [ 5  9 10  3  1  4]
array1 정렬(오름차순): [ 1  3  4  5  9 10]
array1 정렬(인덱싱으로 내림차순 구현): [10  9  5  4  3  1]


In [50]:
array1 = np.array([[5, 9, 10, 3, 1], [8, 3, 4, 2, 5]])
print(f'array1: \n{array1}')
array1.sort(axis=0)
print(f'array1 정렬: \n{array1}')

array1: 
[[ 5  9 10  3  1]
 [ 8  3  4  2  5]]
array1 정렬: 
[[ 5  3  4  2  1]
 [ 8  9 10  3  5]]


### 균일한 간격으로 데이터 생성.

In [51]:
array1 = np.linspace(0, 10, 5)
print(f'array1: {array1}')

array1: [ 0.   2.5  5.   7.5 10. ]


### 난수의 재연(실행마다 결과 동일)

In [69]:
np.random.seed(7)
print(f'난수: \n{np.random.randint(0, 10, (2, 3))}')

난수: 
[[4 9 6]
 [3 3 7]]


### 배열 객체 복사.

In [75]:
array1 = np.arange(0, 10)
print(f'array1: {array1}')
array2 = array1.copy()
print(f'array2: {array2}')
array2[0] = 100
print('')
print(f'array1: {array1}')
print(f'array2: {array2}')

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [0 1 2 3 4 5 6 7 8 9]

array1: [0 1 2 3 4 5 6 7 8 9]
array2: [100   1   2   3   4   5   6   7   8   9]


### 중복된 원소 제거.

In [77]:
array1 = np.array([1, 1, 1, 1, 2, 2, 2, 3, 3, 3, 3 ,4, 4, 4, 5, 5])
print(f'array1: {array1}')
print(f'중복된 값 제거 array1: {np.unique(array1)}')

array1: [1 1 1 1 2 2 2 3 3 3 3 4 4 4 5 5]
중복된 값 제거 array1: [1 2 3 4 5]
